import {
  Box,
  Container,
  Divider,
  Flex,
  Heading,
} from '@chakra-ui/react'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/Header'
import { Banner } from '../components/Banner'
import { TravelTypes } from '../components/TravelTypes'

import { IContinent, SliderContinent } from '../components/SliderContinent'
import api from '../services/api'

interface Page {
  page: string;
  title: string;
  subtitle: string;
  slideTitle: string;
}
interface HomeProps {
  page: Page
  continents: IContinent[]
}

const Home: NextPage<HomeProps> = ({ page, continents }) => {
  return (
    <Flex direction="column">
      <Head>
        <title>World Trip</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Flex
        as="main"
        direction="column"
      >
        <Banner title={page.title} subtitle={page.subtitle} />

        <Container
          as="section"
          maxW="container.xl"
          marginTop={[9, 20]}
          marginBottom={[9, 20]}
        >
          <TravelTypes />

        </Container>
        <Flex
          direction="column"
          as="section"
          marginBottom={[6, 10]}
        >
          <Divider w="48"
            orientation="horizontal"
            borderColor="dark-text"
            borderBottomWidth="2px"
            marginInline="auto"
          />
          <Flex as="header" marginBlockStart={[6, 12]} marginBlockEnd={[5, 12]} >
            <Heading as="h2" fontWeight="medium" textAlign="center" w="100%" fontSize={["xl", "5xl"]}
              dangerouslySetInnerHTML={{ __html: page.slideTitle }} />
          </Flex>
          <Box maxW="container.xl" marginInline="auto">
            <SliderContinent continents={continents} />
          </Box>
        </Flex>
      </Flex>
    </Flex >
  )
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const responsePage = await api.get<Page[]>('/pages', {
    params: {
      page: "Home"
    }
  })
  const responseContinent = await api.get<IContinent[]>('/continents')

  const page = responsePage.data[0]
  const continents = responseContinent.data

  return {
    props: {
      page,
      continents
    }
  }
}


export default Home
